swagger: '2.0'

info:
  $ref: ../yaml/proto/info.yaml

externalDocs:
  $ref: ../yaml/proto/documentation.yaml#/external

tags:
  $ref: ../yaml/proto/documentation.yaml#/categories

schemes:
  $ref: ../yaml/proto/endpoint.yaml#/schemes
host:
  $ref: ../yaml/proto/endpoint.yaml#/server_and_port
basePath:
  $ref: ../yaml/proto/endpoint.yaml#/path

consumes:
  $ref: ../yaml/proto/mediatypes.yaml#/default
produces:
  $ref: ../yaml/proto/mediatypes.yaml#/default

securityDefinitions:
  $ref: ../yaml/proto/security.yaml#/securityDefinitions
security:
  $ref: ../yaml/proto/security.yaml#/defaultSecurity

paths:
  $ref: ../yaml/proto/paths.yaml

definitions:
  $ref: ../yaml/proto/definitions.yaml

responses:
  $ref: ../yaml/proto/responses.yaml

parameters:
  $ref: ../yaml/proto/parameters.yaml
