Ejendomstype:
  name: Ejendomstype
  in: query
  description: Ejendomstype. Angiver hvilken af de tre undertyper (Punkt og flade er slået sammen til én) der ønskes
  type: string
Ejerlavskode:
  name: Ejerlavskode
  in: query
  description: Ejerlavskode. EAID_D16E1BA2_F38E_4cc4_B59E_F35D4ADEE636.EAID_157A3B49_F2FC_4dea_B641_19E46367B721
  type: string
Ejerlejlighednr:
  name: Ejerlejlighednr
  in: query
  description: Ejerlejlighedsnummer. EAID_F33B87C5_ECD5_41d8_879D_53F8B778F32B
  type: string
BFEnr:
  name: BFEnr
  in: query
  description: Et BFENummer eller en liste af BFEnumre på BestemtFastEjendom. EAID_3828326A_2F94_4e83_A24D_F0BBB5D9EC28
  type: string
ELBFEnr:
  name: ELBFEnr
  in: query
  description: BFENummer på Ejerlejlighed. EAID_3828326A_2F94_4e83_A24D_F0BBB5D9EC28
  type: string
BPFGBFEnr:
  name: BPFGBFEnr
  in: query
  description: BFENummer på BygningPaaFremmedGrund. EAID_3828326A_2F94_4e83_A24D_F0BBB5D9EC28
  type: string
JordstykkeId:
  name: JordstykkeId
  in: query
  description: Jordstykke lokalid
  type: string
Point:
  name: point
  in: query
  description: UTM32 etrs89 geometripunkt defineret som indholdet i parentes  fx point=(724786 6176332)
  type: string
  default: "(724786 6176332)"
Matrikelnr:
  name: Matrikelnr
  in: query
  description: Matrikelnummer EAID_8B60BEE8_D3BD_4c07_88FF_A2547A3D82D1.EAID_9C0920E3_3534_492a_978A_D6ED7344379B
  type: string
RekvirentRef:
  name: RekvirentRef
  in: query
  description: EAID_467DE9F6_E982_4a05_A337_F49700FC48E9
  type: string
SagsOperation:
  name: SagsOperation
  in: query
  required: false
  description: Synonym for forretningshændelse. EAID_CE6AEE92_1AD5_4496_8A73_5DF2380A5106
  type: string
SagsKategori:
  name: SagsKategori
  in: query
  required: false
  description: Synonym for forretningsproces. EAID_B8BDA19C_BD3A_45ae_9030_E7DFCEF34409
  type: string
Journalnr:
  name: Journalnr
  in: query
  required: true
  description: journalnummer
  type: string
SagsId:
  name: SagsId
  in: query
  required: false
  description: Sagsid. Reference EAID_9223BE9F_D422_4f05_9180_7D3205A382A9.EAID_9AB90AE0_9F85_4164_9B25_8EB2139D65A5
  type: string
username:
  name: username
  in: path
  required: true
  description: The person's username
  type: string
pageSize:
  name: pageSize
  in: query
  description: Number of records returned
  type: integer
  format: int32
  minimum: 1
  default: 1
pageNumber:
  name: pageNumber
  in: query
  description: Page number
  type: integer
  default: 1
format:
  name: format
  in: query
  description: Output format xml or json
  type: string
  default: json
Kommunenavn:
  name: Kommunenavn
  in: query
  description: Kommunenavn EAID_CBF5C68F_2889_4104_B423_22B718D1DA8B
  type: string
  default: Roskilde
Kommunekode:
  name: Kommunekode
  in: query
  description: Fire-cifret kommunekode EAID_A8B32F95_988E_4efb_B3AD_4920B839393B
  type: string
  pattern: '\d{4}'
  default: '0175'
RegistreringstidFra:
  name: RegistreringstidFra
  in: query
  description: Fra dato i registreringstidsperioden EAID_05A5039B_ACFF_4754_BEA9_BD2EBC8F5C6A
  type: string
  format: date-time
RegistreringstidTil:
  name: RegistreringstidTil
  in: query
  description: Til dato i registreringstidsperioden EAID_6DA20624_44E5_441b_87E4_CDF7765666D7
  type: string
  format: date-time
Registreringstid:
  name: Registreringstid
  in: query
  description: Dato som falder indenfor en registreringstidsperiode. Anvendes fx 2015-09-02 vil de instanser med en gældende registreringstid på denne dato udvælges EAID_05A5039B_ACFF_4754_BEA9_BD2EBC8F5C6A
  type: string
  format: date-time
VirkningstidFra:
  name: VirkningstidFra
  in: query
  description: Fra dato i virkningstidsperioden EAID_E5614463_E808_4491_8205_E30FB93CF3C8
  type: string
  format: date-time
VirkningstidTil:
  name: VirkningstidTil
  in: query
  description: Til dato i virkningstidsperioden EAID_4AE908FA_CBA2_458b_AE3F_C925D5C3A54B
  type: string
  format: date-time
Virkningstid:
  name: Virkningstid
  in: query
  description: Dato som falder indenfor en virkningstidsperiode. Anvendes fx 2015-09-02 vil de instanser med en gældende virkningstid på denne dato udvælges EAID_E5614463_E808_4491_8205_E30FB93CF3C8
  type: string
  format: date-time
Status:
  name: Status
  in: query
  description: Status jf. modellens udfaldsrum EAID_8972BCDE_C722_475d_8E2E_1869DBFAA78D
  type: string
includeNonVerifiedUsers:
  name: includeNonVerifiedUsers
  in: query
  description: Result will not include non verified user by default if this parameter is not provided
  type: boolean
  default: false
  allowEmptyValue: true
sortPersons:
  name: sort
  in: query
  description: Result will be sorted by lastTimeOnline descending and username ascending by default if this parameter is not provided
  type: array
  uniqueItems: true
  minItems: 1
  maxItems: 3
  collectionFormat: pipes
  items:
    type: string
    pattern: '[-+](username|lastTimeOnline|firstname|lastname)'
  default:
    - -lastTimeOnline
    - +username
filterItemTypes:
  name: itemType
  in: query
  description: Filter collected items on their type
  type: array
  collectionFormat: multi
  uniqueItems: true
  items:
    type: string
    enum:
      - AudioCassette
      - Vinyl
      - VHS
userAgent:
  name: User-Agent
  description: All API consumers MUST provide a user agent
  type: string
  in: header
  required: true
SFEBFEnr:
  name: SFEBFEnr
  description: BFE nummer for Samlet Fast Ejendom
  in: query
  type: string
  format: int
  default: 9968514
