pageSize:
  name: pageSize
  in: query
  description: Number of records returned
  type: integer
  format: int32
  minimum: 1
  default: 1
pageNumber:
  name: pageNumber
  in: query
  description: Page number
  type: integer
  default: 1
format:
  name: format
  in: query
  description: Output format xml or json
  type: string
  default: json
