swagger: '2.0'
info:
  version: '3.2'
  title: Services for CPR på Datafordeleren
  description: |
    # CPR #

    ## URL opbygning ##

    URL for de enkelte REST services er opbygget af et endpoint efterfulgt af registernavn, servicenavn, versionen af servicen, servicetype (REST eller WFS etc.)samt metodenavn for REST services. Efter ? tilføjes parametre i kaldet, der kan indeholde generelle kaldeparametre for REST services og metode specifikke parametre.

    Endpointet indeholder værtsnavnet, med et præfiks for miljøet hvis det ikke er produktionsmiljøet der tilgås.  Hvis der er tale om fortrolige eller følsomme data, følger S5. Se miljøbeskrivelser på Datafordeler.dk

    Tjenesterne er specificeret til at give JSON som output, og dette er default såfremt output parameter ikke anvendes. Såfremt der angives XML som output parameter, leveres XML baseret på det specificerede JSON skema:
    * Der udføres samme sæt SQL'er (data fremsøgning) uafhængigt af ønsket format og der hentes kun data der indgår i JSON skemaet.
    * Herefter formateres de fremsøgte data til det ønskede format ud fra JSON skemaet.

    Om output er i XML eller JSON er et spørgsmål om syntaks og påvirker IKKE data indholdet.

    Parameter       |  Værdi |
    --------------- | ---------------------------------------------- |
    Format          | JSON                                           |
    Sikkerhedszone  | 5 - Indeholder fortrolige eller følsomme data. |
    Adgangsniveau   | Indgået aftale med CPR om anvendelse af data påkrævet. |
    Anvendt udstillingsmodel | Person Udstillingsmodel forefindes: http://data.gov.dk/model/diagrammer/ |
    REST-regler     | Anvend paging. Default paging-størrelse: 20 |
    ---------------------------------------------------------------------

schemes:
  - https
host: test03-s5-certservices.datafordeler.dk
basePath: /CPR/CprPrivateAdressName/1/rest/
tags:
  - name: Simpel
    description: Services med garanteret svartider under 0.09 sekund
  - name: Almindelig
    description: Services med svartider mindre end 1.0 sekund
  - name: Kompleks
    description: Services med svartider mindre end 2.5 sekunder
  - name: Offentlige
    description: Services som bruges af det offentlige
  - name: Privat
    description: Services, som bruges af det private
paths:
  /PrivatePersonCurrentAdressName:
    get:
      summary: Find en person
      description: |
        Find en person
        Sikkerhedszone: 5
        Adgangsniveau: Indgået aftale med CPR om anvendelse af data påkrævet.
      tags:
        - Privat
      parameters:
        - $ref: '#/parameters/format'
        - name: cadr.bygningsnummer.eq                                                                                                                                                                             cadr.bygningsnummer.eq
          in: query
          type: string
          required: false
          description: Person.CprAdresse.bygningsnummerLigMed - Bygningsnummer er et persondatafelt, og anvendes på Grønland
        - name: cadr.etage.eq
          in: query
          type: string
          required: false
          description: Person.CprAdresse.etageLigMed - Angivelse af etage i adressen
        - name: cadr.husnummer.eq
          in: query
          type: string
          required: false
          description: Person.CprAdresse.husnummerLigMed - Angiver husnummer for en given bolig
        - name: cadr.postnummer.eq
          in: query
          type: integer
          required: true
          description: Person.CprAdresse.postnummerLigMed - Postnummer, krævet felt
        - name: cadr.sidedoer.eq
          in: query
          type: string
          required: false
          description: Person.CprAdresse.sidedoerLigMed - Sidedør nummer for en bolig
        - name: cadr.vejadresseringsnavn.eq
          type: string
          required: false
          description: Person.CprAdresse.vejadresseringsnavnLigMed - Forkortelse af adresse som bruges ved forsendelser
        - name: navn.efternavn.eq
          type: string
          required: false
          description: Person.Navn.efternavnLigMed - En persons efternavne
        - name: navn.fornavne.eq
          type: string
          required: false
          description: Person.Navn.fornavneLigMed - En persons fornavne og mellemnavne. Konkat af fornavne og mellemnavn
        - $ref: '#/parameters/pageSize'
        - $ref: '#/parameters/pageNumber'
      responses:
        '200':
          description: "Person objekt"
          schema:
            $ref: "schemas/CPR_V3.2_PersonPrivate.json"
  /CprPrivateDaradressName:
    get:
      summary: Private kunders anvendelse af aktuelle CPR data med søgning på DarID og navn.
      description: |
      Private kunders anvendelse af aktuelle CPR data med søgning på DarID og navn.
      Sikkerhedszone: 5
      Adgangsniveau: Indgået aftale med CPR om anvendelse af data påkrævet.
      tags:
        - Privat
      parameters:
        - $ref: '#/parameters/format'
        - name: navn.efternavn.eq
          type: string
          in: query
          description: Person.Navn.efternavnLigMed - En persons efternavn
        - name: navn.fornavne.eq
          type: string
          in: query
          description: Person.Navn.fornavneLigMed - En persons fornavne og mellemnavne. Konkat af fornavne og mellemnavn
        - name: person.foedselsdato.eq
          type: string
          in: query
          description: Person.Person.foedselsdatoLigMed -Angiver hvilken dato fødslen har fundet sted. Datoformat følger ISO 8601
          - $ref: '#/parameters/pageSize'
          - $ref: '#/parameters/pageNumber'
      responses:
        '200':
          description: "Person objekt"
          scehma: "schemas/CPR_V3.2_PersonPrivate.json"

parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of records returned
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
  format:
    name: format
    in: query
    description: Output format xml or json
    type: string
    default: json
