swagger: '2.0'
info:
  version: '3.2'
  title: Services for CPR på Datafordeleren
  description: >
    # CPR #


    ## URL opbygning ##


    URL for de enkelte REST services er opbygget af et endpoint efterfulgt af
    registernavn, servicenavn, versionen af servicen, servicetype (REST eller
    WFS etc.),

    samt metodenavn for REST services.

    Efter ? tilføjes parametre i kaldet, der kan indeholde generelle
    kaldeparametre for REST services og metode specifikke parametre.


    Endpointet indeholder værtsnavnet, med et præfiks for miljøet hvis det ikke
    er produktionsmiljøet der tilgås.

    Hvis der er tale om fortrolige eller følsomme data, følger S5. Se
    miljøbeskrivelser på http://Datafordeler.dk


    Tjenesterne er specificeret til at give JSON som output, og dette er default
    såfremt output parameter ikke anvendes.

    Såfremt der angives XML som output parameter, leveres XML baseret på det
    specificerede JSON skema:

    * Der udføres samme sæt SQL'er (data fremsøgning) uafhængigt af ønsket
    format og der hentes kun data der indgår i JSON skemaet.

    * Herefter formateres de fremsøgte data til det ønskede format ud fra JSON
    skemaet.


    Om output er i XML eller JSON er et spørgsmål om syntaks og påvirker IKKE
    data indholdet.


    Parameter       |  Værdi |

    --------------- | ---------------------------------------------- |

    Format          | JSON                                           |

    Sikkerhedszone  | 5 - Indeholder fortrolige eller følsomme data. |

    Adgangsniveau   | Indgået aftale med CPR om anvendelse af data påkrævet. |

    Anvendt udstillingsmodel | Person Udstillingsmodel forefindes:
    http://data.gov.dk/model/diagrammer/ |

    REST-regler     | Anvend paging. Default paging-størrelse: 20 |

    ---------------------------------------------------------------------

    ### Resultatkoder:

    Der er nedenfor angivet responskoder der er specfikke for de enkelte
    operationer. 

    Der anvendes følgende generelle HTTP Statuskoder:

    * 400 - Bad Request

    * 401 - Unauthorized

    * 403 - Forbidden

    * 406 - Not Acceptable

    * 408 - Request Timeout

    * 415 - Unsupported Media Type

    * 500 - Unexpected failure

    Derudover vil der blive anvendt JSON API fejlkoder [JSON API error
    format](http://jsonapi.org/format/#errors).
schemes:
  - https
host: test03-s5-certservices.datafordeler.dk
basePath: /CPR
tags:
  - name: Offentlige
    description: Services som bruges af det offentlige anvendere.
    externalDocs:
      url: 'http://datafordeler.dk'
  - name: Privat
    description: 'Services, som bruges af det private'
paths:
  /CprPrivatePNR/1/rest/PrivatePersonCurrentPNR:
    get:
      tags:
        - Privat
      produces:
        - application/json
        - application/xml
      summary: Hent en person ud fra personnummeret
      description: Hent en person ud fra personnummeret
      parameters:
        - name: pnr.personnummer.eq
          type: string
          in: query
          required: true
          description: |-
            Person.Personnummer.personnummerLigMed
            Entydig identifikation af en personer i CPR
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                Person:
                  type: object
                  title: Person
                  properties:
                    statusdato:
                      title: statusdato
                      description: EAID_1CB4F47F_E13B_4440_9297_8F25FEC71C49
                      type: string
                      format: date-time
                    statusdatoUsikkerhedsmarkering:
                      title: statusdatoUsikkerhedsmarkering
                      description: EAID_EFF81ED0_3AE0_4535_B0B5_AC4F29FDD5A7
                      type: boolean
                    status:
                      $ref: '#/definitions/PersonStatus'
                    stilling:
                      title: stilling
                      description: EAID_9581CAC7_2F9F_4426_9EC6_3767FA27ECB4
                      type: string
                    Beskyttelser:
                      type: array
                      items:
                        type: object
                        properties:
                          Beskyttelse:
                            $ref: '#/definitions/BeskyttelseUdenVirkningTil'
                    Navn:
                      $ref: '#/definitions/NavnUdenVirkningsperiode'
  /CprPrivateAdressName/1/rest/PrivatePersonCurrentAdressName:
    get:
      summary: Find en person
      description: |
        Find en person

        Sikkerhedszone: 5

        Adgangsniveau: Indgået aftale med CPR om anvendelse af data påkrævet.
      tags:
        - Privat
      parameters:
        - $ref: '#/parameters/format'
        - name: cadr.bygningsnummer.eq
          in: query
          type: string
          required: false
          description: >-
            Person.CprAdresse.bygningsnummerLigMed - Bygningsnummer er et
            persondatafelt, og anvendes på Grønland
        - name: cadr.etage.eq
          in: query
          type: string
          required: false
          description: Person.CprAdresse.etageLigMed - Angivelse af etage i adressen
        - name: cadr.husnummer.eq
          in: query
          type: string
          required: false
          description: >-
            Person.CprAdresse.husnummerLigMed - Angiver husnummer for en given
            bolig
        - name: cadr.postnummer.eq
          in: query
          type: integer
          required: true
          description: 'Person.CprAdresse.postnummerLigMed - Postnummer, krævet felt'
        - name: cadr.sidedoer.eq
          in: query
          type: string
          required: false
          description: Person.CprAdresse.sidedoerLigMed - Sidedør nummer for en bolig
        - name: cadr.vejadresseringsnavn.eq
          in: query
          type: string
          required: false
          description: >-
            Person.CprAdresse.vejadresseringsnavnLigMed - Forkortelse af adresse
            som bruges ved forsendelser
        - name: navn.efternavn.eq
          in: query
          type: string
          required: false
          description: Person.Navn.efternavnLigMed - En persons efternavne
        - name: navn.fornavne.eq
          in: query
          type: string
          required: false
          description: >-
            Person.Navn.fornavneLigMed - En persons fornavne og mellemnavne.
            Konkat af fornavne og mellemnavn
        - $ref: '#/parameters/pageSize'
        - $ref: '#/parameters/pageNumber'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                Person:
                  type: object
                  title: Person
                  properties:
                    statusdato:
                      title: statusdato
                      description: EAID_1CB4F47F_E13B_4440_9297_8F25FEC71C49
                      type: string
                      format: date-time
                    statusdatoUsikkerhedsmarkering:
                      title: statusdatoUsikkerhedsmarkering
                      description: EAID_EFF81ED0_3AE0_4535_B0B5_AC4F29FDD5A7
                      type: boolean
                    status:
                      $ref: '#/definitions/PersonStatus'
                    stilling:
                      title: stilling
                      description: EAID_9581CAC7_2F9F_4426_9EC6_3767FA27ECB4
                      type: string
                    Beskyttelser:
                      type: array
                      items:
                        type: object
                        properties:
                          Beskyttelse:
                            $ref: '#/definitions/BeskyttelseUdenVirkningTil'
                    Navn:
                      $ref: '#/definitions/NavnUdenVirkningsperiode'
        '400':
          description: >-
            Client did something wrong but can fix it (provide another credit
            card number e.g.)
        '401':
          description: Tries to access something that it is not authenticated for.
        '404':
          description: Tries to do something to something that does not exist.
        '500':
          description: Server does not know what happened
  /CPRPrivateDateOfBirth/1/rest/PrivatePersonCurrentDateOfBirthName:
    get:
      summary: >-
        Private kunders anvendelse af aktuelle CPR data med søgning på DarID og
        navn.
      description: >
        Private kunders anvendelse af aktuelle CPR data med søgning på DarID og
        navn.


        Sikkerhedszone 5


        Adgangsniveau Indgået aftale med CPR om anvendelse af data påkrævet.
      tags:
        - Privat
      parameters:
        - name: navn.efternavn.eq
          type: string
          in: query
          description: Person.Navn.efternavnLigMed - En persons efternavn
        - name: navn.fornavne.eq
          type: string
          in: query
          description: >-
            Person.Navn.fornavneLigMed - En persons fornavne og mellemnavne.
            Konkat af fornavne og mellemnavn
        - name: person.foedselsdato.eq
          type: string
          in: query
          description: >-
            Person.Person.foedselsdatoLigMed -Angiver hvilken dato fødslen har
            fundet sted. Datoformat følger ISO 8601
        - $ref: '#/parameters/format'
        - $ref: '#/parameters/pageSize'
        - $ref: '#/parameters/pageNumber'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                Person:
                  type: object
                  title: Person
                  properties:
                    statusdato:
                      title: statusdato
                      description: EAID_1CB4F47F_E13B_4440_9297_8F25FEC71C49
                      type: string
                      format: date-time
                    statusdatoUsikkerhedsmarkering:
                      title: statusdatoUsikkerhedsmarkering
                      description: EAID_EFF81ED0_3AE0_4535_B0B5_AC4F29FDD5A7
                      type: boolean
                    status:
                      $ref: '#/definitions/PersonStatus'
                    stilling:
                      title: stilling
                      description: EAID_9581CAC7_2F9F_4426_9EC6_3767FA27ECB4
                      type: string
                    Beskyttelser:
                      type: array
                      items:
                        type: object
                        properties:
                          Beskyttelse:
                            $ref: '#/definitions/BeskyttelseUdenVirkningTil'
                    Navn:
                      $ref: '#/definitions/NavnUdenVirkningsperiode'
  /CprPrivateDaradressName/1/REST/PrivatePersonCurrentDaradressName:
    get:
      summary: Hent person information
      description: Hent person information
      tags:
        - Privat
      parameters:
        - name: navn.efternavn.eq
          type: string
          in: query
          description: Person.Navn.efternavnLigMed - En persons efternavne
        - name: navn.fornavne.eq
          type: string
          in: query
          description: Person.Navn.fornavneLigMed - En persons fornavne og mellemnavne
        - name: cadr.daradresse.eq
          type: string
          in: query
          description: Person.CprAdresse.daradresseLigMed - Angivelse af adresseUUID
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                Person:
                  type: object
                  title: Person
                  properties:
                    statusdato:
                      title: statusdato
                      description: EAID_1CB4F47F_E13B_4440_9297_8F25FEC71C49
                      type: string
                      format: date-time
                    statusdatoUsikkerhedsmarkering:
                      title: statusdatoUsikkerhedsmarkering
                      description: EAID_EFF81ED0_3AE0_4535_B0B5_AC4F29FDD5A7
                      type: boolean
                    status:
                      $ref: '#/definitions/PersonStatus'
                    stilling:
                      title: stilling
                      description: EAID_9581CAC7_2F9F_4426_9EC6_3767FA27ECB4
                      type: string
                    Beskyttelser:
                      type: array
                      items:
                        type: object
                        properties:
                          Beskyttelse:
                            $ref: '#/definitions/BeskyttelseUdenVirkningTil'
                    Navn:
                      $ref: '#/definitions/NavnUdenVirkningsperiode'
parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of records returned
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
  format:
    name: format
    in: query
    description: Output format xml or json
    type: string
    default: json
definitions:
  PersonStatus:
    title: PersonStatus
    type: string
    enum:
      - annulleret
      - bopael_i_danmark
      - bopael_i_danmark_hoej_vejkode
      - bopael_i_groenland
      - bopael_i_groenland_hoej_vejkode
      - doed
      - ej_bopael
      - forsvundet
      - nedlagt_person
      - udrejst
    example: bopael_i_danmark
  Status:
    title: Status
    type: string
    enum:
      - aktuel
      - fortrudt
      - historisk
      - rettet
      - teknisk_aendring
    example: aktuel
  BeskyttelseUdenVirkningTil:
    title: Beskyttelse
    type: object
    properties:
      beskyttelsestype:
        title: beskyttelsestype
        description: EAID_dst0DF442_9282_4181_B43D_23B02F422804
        type: string
        enum:
          - lokal_vejviser
          - markedsfoering
          - navne_og_adresse
      virkningFra:
        title: virkningFra
        type: string
        description: EAID_8CD2644E_B292_49fd_BCAE_C7B94BE550E9
        format: date-time
    required:
      - beskyttelsestype
  NavnUdenVirkningsperiode:
    title: Navn
    type: object
    properties:
      adresseringsnavn:
        title: adresseringsnavn
        description: EAID_2B7D329F_7E3B_4bce_85BC_2B084619649D
        type: string
      efternavn:
        title: efternavn
        description: EAID_D3E09BDA_7174_4555_92F0_A7093671DCCF
        type: string
      fornavne:
        title: fornavne
        description: EAID_C83C2BED_DA60_4017_B446_044A502AFE01
        type: string
      mellemnavn:
        title: mellemnavn
        description: EAID_6503AA6C_33D3_4baa_AD1A_5D7FED741A2B
        type: string
      efternavnsmarkering:
        $ref: '#/definitions/Navnemarkering'
      fornavnsmarkering:
        $ref: '#/definitions/Navnemarkering'
      mellemnavnsmarkering:
        $ref: '#/definitions/Navnemarkering'
      status:
        $ref: '#/definitions/Status'
    additionalProperties: false
    required:
      - status
  Navnemarkering:
    type: string
    title: Navnemarkering
    description: Anvendes til at angive dokumentationsniveauet for navnet
    enum:
      - forkortet
      - indeholder_tegn_der_ikke_kan_indrapporteres_til_cpr
      - utilstraekkeligt_dokumenteret
properties:
  Personer:
    title: Personer
    type: array
    items:
      type: object
      properties:
        Person:
          type: object
          title: Person
          properties:
            statusdato:
              title: statusdato
              description: EAID_1CB4F47F_E13B_4440_9297_8F25FEC71C49
              type: string
              format: date-time
            statusdatoUsikkerhedsmarkering:
              title: statusdatoUsikkerhedsmarkering
              description: EAID_EFF81ED0_3AE0_4535_B0B5_AC4F29FDD5A7
              type: boolean
            status:
              $ref: '#/definitions/PersonStatus'
            stilling:
              title: stilling
              description: EAID_9581CAC7_2F9F_4426_9EC6_3767FA27ECB4
              type: string
