swagger: '2.0'
info:
  version: '1.0'
  title: 'https://test03-services.datafordeler.dk'
basePath: '/DAR/DAR/1/rest'
paths:
  /adresse:
    get:
      operationId: Adresse
      parameters:
        - name: Id
          in: query
          required: false
          type: string
        - name: Format
          in: query
          required: false
          type: string
        - name: Count
          in: query
          required: false
          type: string
        - name: VirkningFra
          in: query
          required: false
          type: string
        - name: VirkningTil
          in: query
          required: false
          type: string
        - name: Virkningsaktoer
          in: query
          required: false
          type: string
        - name: RegistreringFra
          in: query
          required: false
          type: string
        - name: RegistreringTil
          in: query
          required: false
          type: string
        - name: Registreringsaktoer
          in: query
          required: false
          type: string
        - name: Status
          in: query
          required: false
          type: string
        - name: Forretningsproces
          in: query
          required: false
          type: string
        - name: Forretningsomraade
          in: query
          required: false
          type: string
        - name: Forretningshaendelse
          in: query
          required: false
          type: string
        - name: MedDybde
          in: query
          required: false
          type: string
        - name: Husnummer
          in: query
          required: false
          type: string
        - name: Bygning
          in: query
          required: false
          type: string
        - name: NavngivenVej
          in: query
          required: false
          type: string
        - name: NavngivenVejKommunedel
          in: query
          required: false
          type: string
        - name: Kommunekode
          in: query
          required: false
          type: string
        - name: Vejkode
          in: query
          required: false
          type: string
        - name: Nord
          in: query
          required: false
          type: string
        - name: Syd
          in: query
          required: false
          type: string
        - name: Oest
          in: query
          required: false
          type: string
        - name: Vest
          in: query
          required: false
          type: string
        - name: DAFTimestampFra
          in: query
          required: false
          type: string
        - name: DAFTimestampTil
          in: query
          required: false
          type: string
      responses:
  /husnummer:
    get:
      operationId: husnummer
      parameters:
        - name: Id
          in: query
          required: false
          type: string
        - name: format
          in: query
          required: false
          type: string
        - name: count
          in: query
          required: false
          type: string
        - name: Virkningsaktoer
          in: query
          required: false
          type: string
        - name: Registreringsaktoer
          in: query
          required: false
          type: string
        - name: Forretningshaendelse
          in: query
          required: false
          type: string
        - name: Forretningsomraade
          in: query
          required: false
          type: string
        - name: Forretningsproces
          in: query
          required: false
          type: string
        - name: Status
          in: query
          required: false
          type: string
        - name: VirkningFra
          in: query
          required: false
          type: string
        - name: VirkningTil
          in: query
          required: false
          type: string
        - name: RegistreringFra
          in: query
          required: false
          type: string
        - name: RegistreringTil
          in: query
          required: false
          type: string
        - name: MedDybde
          in: query
          required: false
          type: string
        - name: AdgangTilBygning
          in: query
          required: false
          type: string
        - name: AdgangTilTekniskAnlaeg
          in: query
          required: false
          type: string
        - name: Grund
          in: query
          required: false
          type: string
        - name: NavngivenVej
          in: query
          required: false
          type: string
        - name: Adresse
          in: query
          required: false
          type: string
        - name: Postnr
          in: query
          required: false
          type: string
        - name: NavngivenVejKommunedel
          in: query
          required: false
          type: string
        - name: Jordstykke
          in: query
          required: false
          type: string
        - name: Vejkode
          in: query
          required: false
          type: string
        - name: Opgang
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAR
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAGI
          in: query
          required: false
          type: string
        - name: Postnummer
          in: query
          required: false
          type: string
        - name: Postnummerinddeling
          in: query
          required: false
          type: string
        - name: Afstemningsomraade
          in: query
          required: false
          type: string
        - name: Sogneinddeling
          in: query
          required: false
          type: string
        - name: Kommuneinddeling
          in: query
          required: false
          type: string
        - name: Menighedsraadsafstemningsomraade
          in: query
          required: false
          type: string
        - name: Vejmidte
          in: query
          required: false
          type: string
        - name: GeoDanmarkBygning
          in: query
          required: false
          type: string
        - name: Nord
          in: query
          required: false
          type: string
        - name: Syd
          in: query
          required: false
          type: string
        - name: Oest
          in: query
          required: false
          type: string
        - name: Vest
          in: query
          required: false
          type: string
        - name: DAFTimestampTil
          in: query
          required: false
          type: string
        - name: DAFTimestampFra
          in: query
          required: false
          type: string
      responses:
  /navngivenvejkommunedel:
    get:
      operationId: navngivenvejkommunedel
      parameters:
        - name: Id
          in: query
          required: false
          type: string
        - name: Format
          in: query
          required: false
          type: string
        - name: count
          in: query
          required: false
          type: string
        - name: VirkningFra
          in: query
          required: false
          type: string
        - name: VirkningTil
          in: query
          required: false
          type: string
        - name: Virkningsaktoer
          in: query
          required: false
          type: string
        - name: RegistreringFra
          in: query
          required: false
          type: string
        - name: RegistreringTil
          in: query
          required: false
          type: string
        - name: Registreringsaktoer
          in: query
          required: false
          type: string
        - name: Status
          in: query
          required: false
          type: string
        - name: Forretningshaendelse
          in: query
          required: false
          type: string
        - name: Forretningsomraade
          in: query
          required: false
          type: string
        - name: Forretningsproces
          in: query
          required: false
          type: string
        - name: MedDybde
          in: query
          required: false
          type: string
        - name: Schema
          in: query
          required: false
          type: string
        - name: Kommunekode
          in: query
          required: false
          type: string
        - name: NavngivenVej
          in: query
          required: false
          type: string
        - name: Vejkode
          in: query
          required: false
          type: string
        - name: Husnummer
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAR
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAGI
          in: query
          required: false
          type: string
        - name: Postnummer
          in: query
          required: false
          type: string
        - name: Postnummerinddeling
          in: query
          required: false
          type: string
        - name: Adresse
          in: query
          required: false
          type: string
        - name: DAFTimestampFra
          in: query
          required: false
          type: string
        - name: DAFTimestampTil
          in: query
          required: false
          type: string
        - name: pagesize
          in: query
          required: false
          type: string
      responses:
  /postnummer:
    get:
      operationId: postnummer
      parameters:
        - name: Id
          in: query
          required: false
          type: string
        - name: Format
          in: query
          required: false
          type: string
        - name: Count
          in: query
          required: false
          type: string
        - name: VirkningFra
          in: query
          required: false
          type: string
        - name: VirkningTil
          in: query
          required: false
          type: string
        - name: Virkningsaktoer
          in: query
          required: false
          type: string
        - name: RegistreringFra
          in: query
          required: false
          type: string
        - name: RegistreringTil
          in: query
          required: false
          type: string
        - name: Registreringsaktoer
          in: query
          required: false
          type: string
        - name: Status
          in: query
          required: false
          type: string
        - name: Forretningsproces
          in: query
          required: false
          type: string
        - name: Forretningsomraade
          in: query
          required: false
          type: string
        - name: Forretningshaendelse
          in: query
          required: false
          type: string
        - name: MedDybde
          in: query
          required: false
          type: string
        - name: Navn
          in: query
          required: false
          type: string
        - name: Postnr
          in: query
          required: false
          type: string
        - name: Postnummerinddeling
          in: query
          required: false
          type: string
        - name: DAFTimestampFra
          in: query
          required: false
          type: string
        - name: DAFTimestampTil
          in: query
          required: false
          type: string
      responses:
  /navngivenvej:
    get:
      operationId: navngivenvej
      parameters:
        - name: Id
          in: query
          required: false
          type: string
        - name: Format
          in: query
          required: false
          type: string
        - name: count
          in: query
          required: false
          type: string
        - name: VirkningFra
          in: query
          required: false
          type: string
        - name: VirkningTil
          in: query
          required: false
          type: string
        - name: Virkningsaktoer
          in: query
          required: false
          type: string
        - name: RegistreringFra
          in: query
          required: false
          type: string
        - name: RegistreringTil
          in: query
          required: false
          type: string
        - name: Registreringsaktoer
          in: query
          required: false
          type: string
        - name: Status
          in: query
          required: false
          type: string
        - name: Forretningshaendelse
          in: query
          required: false
          type: string
        - name: Forretningsomraade
          in: query
          required: false
          type: string
        - name: Forretningsproces
          in: query
          required: false
          type: string
        - name: MedDybde
          in: query
          required: false
          type: string
        - name: Kommunekode
          in: query
          required: false
          type: string
        - name: Vejkode
          in: query
          required: false
          type: string
        - name: Husnummer
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAR
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAGI
          in: query
          required: false
          type: string
        - name: Postnummer
          in: query
          required: false
          type: string
        - name: Postnummerinddeling
          in: query
          required: false
          type: string
        - name: Adresse
          in: query
          required: false
          type: string
        - name: DAFTimestampTil
          in: query
          required: false
          type: string
        - name: DAFTimestampFra
          in: query
          required: false
          type: string
        - name: pagesize
          in: query
          required: false
          type: string
      responses:
  /supplerendebynavn:
    get:
      operationId: supplerendebynavn
      parameters:
        - name: Id
          in: query
          required: false
          type: string
        - name: Format
          in: query
          required: false
          type: string
        - name: Count
          in: query
          required: false
          type: string
        - name: VirkningFra
          in: query
          required: false
          type: string
        - name: VirkningTil
          in: query
          required: false
          type: string
        - name: Virkningsaktoer
          in: query
          required: false
          type: string
        - name: RegistreringFra
          in: query
          required: false
          type: string
        - name: RegistreringTil
          in: query
          required: false
          type: string
        - name: Registreringsaktoer
          in: query
          required: false
          type: string
        - name: Status
          in: query
          required: false
          type: string
        - name: Forretningsproces
          in: query
          required: false
          type: string
        - name: Forretningsomraade
          in: query
          required: false
          type: string
        - name: Forretningshaendelse
          in: query
          required: false
          type: string
        - name: MedDybde
          in: query
          required: false
          type: string
        - name: Navn
          in: query
          required: false
          type: string
        - name: SupplerendeBynavnDAGI
          in: query
          required: false
          type: string
        - name: DAFTimestampFra
          in: query
          required: false
          type: string
        - name: DAFTimestampTil
          in: query
          required: false
          type: string
      responses: